In [118]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    root_mean_squared_error,
    r2_score,
)

import joblib
import pandas as pd
import os

In [119]:
DATASET_FILE: str = "data.csv"
TRAIN_COLUMNS: list[str] = {
    "frequency",
    "attack-angle",
    "chord-length",
    "free-stream-velocity",
    "suction-side-displacement-thickness",
}
TARGET_COLUMN: str = "scaled-sound-pressure"
RANDOM_SEED: int = 42
TEST_SIZE: float = 0.2
SAVE_DATA_PATH: str = "data"

In [120]:
df = pd.read_csv(DATASET_FILE)

df.head()

,frequency,attack-angle,chord-length,free-stream-velocity,suction-side-displacement-thickness,scaled-sound-pressure
0,800,0.0,0.3048,71.3,0.002663,126.201
1,1000,0.0,0.3048,71.3,0.002663,125.201
2,1250,0.0,0.3048,71.3,0.002663,125.951
3,1600,0.0,0.3048,71.3,0.002663,127.591
4,2000,0.0,0.3048,71.3,0.002663,127.461

In [121]:
train_df = df[list(TRAIN_COLUMNS)]
train_df.head()

,frequency,suction-side-displacement-thickness,attack-angle,chord-length,free-stream-velocity
0,800,0.002663,0.0,0.3048,71.3
1,1000,0.002663,0.0,0.3048,71.3
2,1250,0.002663,0.0,0.3048,71.3
3,1600,0.002663,0.0,0.3048,71.3
4,2000,0.002663,0.0,0.3048,71.3

In [122]:
target_df = df[list([TARGET_COLUMN])]
target_df.head()

   scaled-sound-pressure
0                126.201
1                125.201
2                125.951
3                127.591
4                127.461

In [123]:
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
X_train, X_test, y_train, y_test = train_test_split(
    train_df,
    target_df,
    test_size=TEST_SIZE,
    random_state=RANDOM_SEED,
    shuffle=True,
)

pass

In [124]:
X_train_scaled_np = X_train.to_numpy()
X_test_scaled_np = X_test.to_numpy()

In [125]:
y_train_np = y_train.to_numpy()
y_test_np = y_test.to_numpy()

In [126]:
X = X_train_scaled_np
y = y_train_np

# https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html
model = RandomForestRegressor(
    n_estimators=10,
    random_state=RANDOM_SEED,
)

model.fit(X, y.ravel())

RandomForestRegressor(n_estimators=10, random_state=42)

In [127]:
score = model.score(X_test_scaled_np, y_test)
score

0.936925110718367

In [128]:
y_pred = model.predict(X_test_scaled_np)

# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_error.html
mae = mean_absolute_error(y_test, y_pred)

# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html
mse = mean_squared_error(y_test, y_pred)

# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.root_mean_squared_error.html
rmse = root_mean_squared_error(y_test, y_pred)

# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html
r2 = r2_score(y_test, y_pred)

print(f'MAE: "{mae:.2f}" (~1% average absolute error relative to target values)')
print(f'MSE: "{mse:.2f}" (mean squared prediction error, lower is better)')
print(f'RMSE: "{rmse:.2f}" (prediction error in the same units as the target variable)')
print(f'R2: "{r2:.2f}" ("1.0" is the best possible score)')

MAE: "1.31" (~1% average absolute error relative to target values)
MSE: "3.16" (mean squared prediction error, lower is better)
RMSE: "1.78" (prediction error in the same units as the target variable)
R2: "0.94" ("1.0" is the best possible score)

In [129]:
print("Save model")


if not os.path.exists(SAVE_DATA_PATH):
    os.mkdir(SAVE_DATA_PATH)

joblib.dump(model, f"{SAVE_DATA_PATH}/random_forest_model.pkl")

Save model

['data/random_forest_model.pkl']